config/routes.rb
Rails.application.routes.draw do
  root "pictures#index"
  resources :pictures do
    collection do
      post :confirm
    end
  end
  devise_for :users
  resources :users, :only => [:show,:favorite] do
    member do
      get :favorite
    end
  end
  resources :favorites, only:[:create,:destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url,notice: "#{favorite.picture.user.name}さんの投稿をお気に入りしました！"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブ投稿をお気に入り解除しました"
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all
    @picture = current_user.id
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
    @picture = Picture.new(picture_params)
    else
    @picture = Picture.new
    end
  end

  def edit
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    respond_to do |format|
      if @picture.save
        ContributeMailer.contribute_mail(@picture).deliver
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def favorite
    @user = User.find(params[:id])
    @favorites_pictures = @user.favorite_pictures
  end

  def show
    @user = User.find(params[:id])
    @favorites_pictures = @user.favorite_pictures
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snappee</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <!-- ナビバー -->
      <header>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
                <span class="sr-only">Snappee</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">
                <%= image_tag('logo1.png',:size => "125x30",:alt => "ロゴ") %>
              </a>
            </div>
              <div id="gnavi" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                  <% if user_signed_in? %>
                  <li>
                    <%= link_to '＋New Snap!!', new_picture_path %>
                  </li>
                  <li>
                    <a href="/users/<%= current_user.id %>">Mypage</a>
                  </li>
                  <li>
                    <a class="nav-link" href="/users/<%= current_user.id %>/favorite">favorite</a>
                  </li>
                  <li>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                  </li>
                  <% end %>
                </ul>
              </div>
          </div>
        </nav>
      </heder>

  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>

  <footer>
    <p class="mt-5 mb-3 text-muted text-center">&copy; 2018 Snappee.inc</p>
  </footer>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true,url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image.url %>
    <%= form.file_field :image ,id: :picture_image %>
  </div>
  <div class="form-group">
    <%= form.text_field :title, id: :picture_title, class:"form-control", placeholder:"Title" %>
  </div>

  <div class="form-group">
    <%= form.text_area :content, id: :picture_content, class:"form-control", placeholder:"Content" %>
  </div>
  <div class="actions">
    <%= form.submit "Snap!!", :class=>"btn btn-success" %>
  </div>

<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で投稿する</h3>

<%= form_with(model: @picture,url: pictures_path,local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <p><%= image_tag(@picture.image) %></p>
  <p>タイトル:<%= @picture.title %></p>
  <p>本文:<%= @picture.content %></p>
  <%= form.submit "投稿する",:class=>"btn btn-primary" %>
  <% end %>

<%= form_with(model: @picture,url:new_picture_path,local: true,method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: 'back',:class=>"btn btn-default" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
  <div class="row">
    <% @pictures.each do |picture| %>
        <div class="col-md-6">
        <div class="thumbnail">
          <% post_user = picture.user %>
          <h4 class="text-right">投稿者:<%= post_user.try(:name) %></h4>
          <hr>
          <%= image_tag(picture.image) %>
          <div class="caption">
            <hr>
            <h4><%= picture.title %></h4>
            <p><%= picture.content %></p>
            <p><%= link_to 'Show', picture,class: "btn btn-success",style: "color:white;" %>
            <% unless @picture != picture.user.id %>
              <%= link_to 'Edit', edit_picture_path(picture),class: "btn btn-primary", style: "color:white;", role:"button" %>
              <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger",style: "color:white;", role:"button" %></p>
            <% end %>
            <br>
            <%= picture.created_at %>
          </div>
        </div>
        </div>
    <% end %>
  </div>

app/views/pictures/new.html.erb
<h1 >New Snap!!</h1>
<%= render 'form', picture: @picture %>

<%= link_to '<<Back', pictures_path %>

app/views/pictures/show.html.erb
<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image %>
</p>
<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id, picture_id: @picture.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<br>
<%= @picture.created_at %>
<br>
<br>
<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/users/favorite.html.erb
<div class="row">
  <h2>お気に入り一覧</h2>
  <% @favorites_pictures.each do |favorite| %>
      <div class="col-md-6">
      <div class="thumbnail">
        <h4 class="text-right">投稿者：</span>:<%= favorite.user.name %></h4>
        <hr>
        <%= image_tag(favorite.image) %>
        <div class="caption">
          <hr>
          <h4><%= favorite.title %></h4>
          <p><%= favorite.content %></p>
        </div>
      </div>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %>のMy page </h1>
<p>email:<%= @user.email %></p>
<%= link_to '新しくブログを投稿する', new_picture_path, class:'btn btn-primary',style: "color:white;" %>